
name: Build and Deploy with echo

on:
 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    
    steps:  
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.1
        with:
          version: 12.x
      - run: |
          yarn install --production
          yarn build
      - uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - run: ls -la
      - run: aws s3 sync ./public s3://alpacked-e49cf8e
